services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<TIMEZONE>
      - USER=<USERNAME>
      - PASS=<PASSWORD>
    volumes:
      - ./config:/config
      - <DOWNLOADS_PATH>:/downloads
      - <WATCH_PATH>:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped